name: "Home Assistant Fast Config Check"
author: "Kevin Stark <kev.stark@gmail.com>"
description: "Check your configuration for Home Assistant."
inputs:
  config_path:
    description: "Relative path to your configuration directory if not in the root"
    required: false
    default: ''
runs: 
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'home'  
  color: 'blue'
