name: "Capture Home Assistant Release"

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    name: Check Latest Home Assistant Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Package configurations
    - name: Capture latest release
      run: |
        cat .HA_VERSION
        curl -s https://github.com/home-assistant/core/releases/latest | egrep -o '(?[0-9|.]{5,})' > .HA_VERSION
        cat .HA_VERSION

    - name: Commit files
      run: |
        git config --local user.name ${{ github.actor }}
        git config --local user.email ${{ github.actor}}@users.noreply.github.com
        git add .HA_VERSION
        git commit -m "version bump"
      continue-on-error: true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
      continue-on-error: true
